my_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: vetxnmg-zg93609
      user: thunder
      password: Thunder@67
      role: ACCOUNTADMIN
      database: BRONZE
      warehouse: COMPUTE_WH
      schema: POS   
    prod:
      type: snowflake
      account: vetxnmg-zg93609
      user: thunder
      password: Thunder@67
      role: ACCOUNTADMIN
      database: SILVER
      warehouse: COMPUTE_WH
      schema: TRANSFORMED_POS